### ISSUE TITLE
iOS build target is currently 5.1.1

### ISSUE THREAD

**Issue by kurgol** [Kurgol/samba-action-calculator#2]
The minimum target for xcode 8 is at present iOS 8.

**Comment by chris-shortall** [comment]
Looking at the current stats, 98% of iPhone users are on iOS 9 or higher, and 95% are on 10 or 11.  Shall we have the minimum target iOS 9 to begin with, and consider increasing to 10 later if required?

**Comment by kurgol** [comment]
I think I'd like to keep the minimum target as broad as possible, though I am not set on this and I am open to being persuaded (iOS 8 could still be running on iPhone 5)

**Comment by chris-shortall** [comment]
The main reason would be to take advantage of new APIs, however that decision can be made later if it's necessary when updating the rest of the app.

**Comment by kurgol** [comment]
Yeah that's what I thought. I would like to get this app back in the store with as few changes as possible and just get in back in use. I may open a develop-next branch for future work, as I would eventually like an iOS/Android app sharing a codebase, which probably means moving to phonegap (or similar) to build future versions.

Not ruling out changing the iOS build target to 9, but only if we actually start using the newer api's that require it.

**Comment by Kurgol** [comment]
solved by #7

**Comment by kurgol** [comment]
solved by #7
