### ISSUE TITLE
Player name is not visible

### ISSUE THREAD

**Issue by chris-shortall** [Kurgol/samba-action-calculator#4]
Looks like white text on a white background

![simulator screen shot 13 oct 2017 08 57 11](https://user-images.githubusercontent.com/1537138/31539748-7d8ab70a-b001-11e7-930f-7fc231f48328.png)

**Comment by kurgol** [comment]
Confirmed I can replicate this in the simulator - however when I press and hold the selection the player name becomes visible so likely we just need to change the text colour.

**Comment by kurgol** [comment]
should be resolved by pr #10
