### ISSUE TITLE
Tapping the (i) button next to player name does nothing

### ISSUE THREAD

**Issue by chris-shortall** [Kurgol/samba-action-calculator#5]
I would expect this to open the player details to view/edit their skills like Dodge.

**Comment by kurgol** [comment]
If you click anywhere on the row other than the "i" it does, not sure what the intended behaviour was in the original app, but agree behaviour is not ideal.

**Comment by Kurgol** [comment]
should be resolved by #11

**Comment by kurgol** [comment]
should be resolved by #11
