### ISSUE TITLE
Selected actions do not appear in the "grey block"

### ISSUE THREAD

**Issue by chris-shortall** [Kurgol/samba-action-calculator#6]
And the end percentage is not changed.

![simulator screen shot 13 oct 2017 10 37 02](https://user-images.githubusercontent.com/1537138/31540076-7d2f9400-b002-11e7-9d86-c3686a241a28.png)

**Comment by kurgol** [comment]
Yeah, I can also replicate this in the simulator. I'm hoping like player names it's just a display bug, but will need to investigate in more detail.

**Comment by kurgol** [comment]
I think this is just a shit UI @chris-shortall-tessella - now that you have fixed the text appearing on the black background, once I have queued up a skill with the relevant options, say dodge with 3+ highlighted. When I double tap where it says dodge (highlighted red in attached screenshot) it does add the skill to the list of queued commands.
![screenshot](https://user-images.githubusercontent.com/15245142/31604519-7c1f2b24-b25b-11e7-8517-d12471c5b54e.png)

**Comment by chris-shortall** [comment]
Yes indeed!  Happy to leave it as it is for now?  Not ideal, but it "works", and a UI refresh is on the roadmap ;)

**Comment by kurgol** [comment]
I mean it should look like a button right, that seems like the obvious fix. I would accept a pull request to change the appearance, but as you say this shouldn't roadblock a release.
