### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by kurgol** [Kurgol/samba-action-calculator#8]
I want to bump the version number of the app for the develop branch. Is this just as straightforward as bumping the following code in samba-action-calculator/Samba Action Calculator/Samba Action Calculator-Info.plist:

```
	<key>CFBundleShortVersionString</key>
	<string>1.0.2</string>
	...
	<key>CFBundleVersion</key>
	<string>1.0.2</string>
```

Want to know if there are any implied repercussions for version number changes, or if there is anything appley that I need to know specifically.

**Comment by chris-shortall** [comment]
Basically yeah, it's that straightforward :) `CFBundleShortVersionString` is the visible app version number, and `CFBundleVersion` is usually used as an internal build number, but is fine to just match it to the app version number if you're not worried about tracking releases etc.

**Comment by kurgol** [comment]
Great!

**Comment by kurgol** [comment]
manually updated the two properties in the file, probably bad way to do it as no pull request to track - however trying to work out how to update the properties of those two fields in xcode was starting to become frustrating.

updated both to 1.0.2

**Comment by chris-shortall** [comment]
FYI you can do it here:

<img width="1281" alt="screen shot 2017-10-16 at 12 57 33" src="https://user-images.githubusercontent.com/1537138/31610871-b1f7e518-b271-11e7-861a-e2dd4fe8939c.png">

**Comment by kurgol** [comment]
ahh thanks that would be it. I was trying to update the file Samba Action Calculator/samba-action-calculatorinfo.plist directly and in xcode that is an uneditable property page.

I ended up doing it via github edit, which seemed daft.
